# {{.API.Name}} CRUD generated by gogenetic
A Go micro services eco-system, designed to make development and maintaince of microservice life easier.

# Goal
To make application CRUD application with GRPC, HTTP, DB support & External config in golang



# Build Gogenetic
    cd crud
    go build cmd/main/{{.API.Name}}-cmdserver.go
    

# Run Gogenetic

    cd crud
    ./{{.API.Name}}-cmdserver

## Config Supported

    External Config File to load Port and DB Connection

    config-dev.json

    {
    "GRPCPort": 4040,
    "HTTPPort": 8080,
    "DBCon": "root:@tcp(localhost:3306)/GOGENETIC_SCHEMA?charset=utf8&parseTime=True&loc=Local",
    "NATSurl": "nats://127.0.0.1:4222",
    "UserCreds":"",
    "ShowTime":true
    }

    