# This is a TOML Support CRUD & EventSourcing Architechture

[Architechture]
Name = "es"

[API]
Name = "JWT"
Operations = [ { url = "/jwt/generate" , request = "JWTCreateRequest" , response = "JWTCreateResponse", protocol = "POST" , operationid  = "Create"},
               { url = "/jwt/renew/{jWTToken}" , request = "JWTRenewRequest" , response = "JWTRenewResponse", protocol = "PUT" , operationid  = "Update"},
               { url = "/jwt/verify/{jWTToken}" , request = "JWTVerifyRequest" , response = "JWTVerifyResponse", protocol = "DELETE" , operationid  = "Delete"}]



[Models]
Model = [{ name = "JWTToken" , Variable = [{ name = "user", value = "1" , type = "string"  },{ name = "token", value = "1" , type = "string"  }] },
        { name = "JWTCreateRequest" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "jWTToken", value = "jWTToken" , type = "object" ,  parameter="body" }] },
        { name = "JWTCreateResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "jWTToken", value = "token" , type = "object" , modelVal = "JWTToken" }] },
        { name = "JWTRenewRequest" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = " jWTToken", value = "jWTToken" , type = "string" ,  parameter="path"  }] },
        { name = "JWTRenewResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "jWTToken", value = "token" , type = "object" , modelVal = "JWTToken" }] },
        { name = "JWTVerifyRequest" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "jWTToken", value = "jWTToken" , type = "string" , parameter="path"  }] },
        { name = "JWTVerifyResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "status", value = "true" , type = "boolean" ,  modelVal = "JWTToken"}] } ]

[DomainModels]
DomainModel = [{ name = "JWTTokenDomains" , Variable = [{ name = "User", value = "1" , type = "string"  },{ name = "Token", value = "1" , type = "string"  }] }]


[Mapping]
Map = [{ name = "convertJWTTokenDomainJWTToken" , from = "JWTTokenDomains" , to = "JWTToken" , type="domain2dto", primary = "Token" , primarytype = "string" , VariableMapping = [{ from = "User", to = "User" , type="string"   },{ from = "Token", to = "Token"  }]},
     { name = "convertJWTTokenoJWTTokenDomain" , from = "JWTToken" , to = "JWTTokenDomains" , type="dto2domain", VariableMapping = [{ from = "User", to = "User" , type="string" },{ from = "Token", to = "Token" }]} ]

[CommandToEvent]
Command =  [{name = "JWTCreatedCommand", events= [{name = "JWTTokenDomainsEventCreated"}]},
            {name = "JWTUpdatedCommand", events= [{name = "JWTTokenDomainsEventUpdated"}]}]