# This is a TOML grpc document

[API]
Name = "Test"
Operations = [ { operation = "/add" , request = "AddReq" , response = "AddRes", protocol = "POST" } ]



[Models]
Model = [{ name = "AddReq", Variable = [{ name = "a", value = "1" , type = "int" } , { name = "b", value = "2" , type = "int" }] },
        { name = "AddRes", Variable = [{ name = "result", value = "1" , type = "int" } ] }]