# This is a TOML Support CRUD & EventSourcing Architechture

[Architechture]
Name = "es-rest"

[API]
Name = "Test"
Operations = [ { url = "/todo/all" , request = "ReadAllRequest" , response = "ReadAllResponse", protocol = "GET" , operationid  = "ReadAll"},
               { url = "/todo" , request = "CreateRequest" , response = "CreateResponse", protocol = "POST" , operationid  = "Create"},
               { url = "/todo/{id}" , request = "UpdateRequest" , response = "UpdateResponse", protocol = "PUT" , operationid  = "Update"},
               { url = "/todo/{id}" , request = "DeleteRequest" , response = "DeleteResponse", protocol = "DELETE" , operationid  = "Delete"},
               { url = "/todo/{id}" , request = "ReadRequest" , response = "ReadResponse", protocol = "GET" , operationid  = "Read"}]



[Models]
Model = [{ name = "ToDo" , Variable = [{ name = "id", value = "1" , type = "int"  },{ name = "title", value = "1" , type = "string"  }] },
        { name = "ReadAllRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" }] },
        { name = "ReadAllResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "toDos", value = "list" , type = "repeated" } ] },
        { name = "CreateRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "toDo", value = "toDo" , type = "object" , parameter="body" }] },
        { name = "CreateResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "id", value = "1" , type = "int" , modelVal = "ToDo" }] },
        { name = "UpdateRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "id", value = "1" , type = "int" , parameter="path" },{ name = "toDo", value = "toDo" , type = "object" , parameter="body"}] },
        { name = "UpdateResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "id", value = "1" , type = "int" , modelVal = "ToDo" }] },
        { name = "DeleteRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "id", value = "1" , type = "int" , parameter="path" }] },
        { name = "DeleteResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "deleted", value = "true" , type = "boolean" }] },
        { name = "ReadRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query"  },{ name = "id", value = "1" , type = "int" , parameter="path" }] },
        { name = "ReadResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "toDo", value = "toDo" , type = "object" }] } ]
