# This is a TOML Support CRUD & EventSourcing Architechture

[Architechture]
Name = "es"

[API]
Name = "Todo"
Operations = [ { url = "/todo/all" , request = "ReadAllRequest" , response = "ReadAllResponse", protocol = "GET" , operationid  = "ReadAll"},
               { url = "/todo" , request = "CreateRequest" , response = "CreateResponse", protocol = "POST" , operationid  = "Create"},
               { url = "/todo/{id}" , request = "UpdateRequest" , response = "UpdateResponse", protocol = "PUT" , operationid  = "Update"},
               { url = "/todo/{id}" , request = "DeleteRequest" , response = "DeleteResponse", protocol = "DELETE" , operationid  = "Delete"},
               { url = "/todo/{id}" , request = "ReadRequest" , response = "ReadResponse", protocol = "GET" , operationid  = "Read"}]



[Models]
Model = [{ name = "ToDo" , Variable = [{ name = "id", value = "1" , type = "int"  },{ name = "title", value = "1" , type = "string"  }] },
        { name = "ReadAllRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" }] },
        { name = "ReadAllResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "toDos", value = "list" , type = "repeated" } ] },
        { name = "CreateRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "toDo", value = "toDo" , type = "object" , parameter="body" }] },
        { name = "CreateResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "id", value = "1" , type = "int" }] },
        { name = "UpdateRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "id", value = "1" , type = "int" , parameter="path" },{ name = "toDo", value = "toDo" , type = "object" , parameter="body"}] },
        { name = "UpdateResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "updated", value = "1" , type = "int" }] },
        { name = "DeleteRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query" },{ name = "id", value = "1" , type = "int" , parameter="path" }] },
        { name = "DeleteResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "deleted", value = "true" , type = "boolean" }] },
        { name = "ReadRequest" , Variable = [{ name = "v1", value = "1" , type = "int" , parameter="query"  },{ name = "id", value = "1" , type = "int" , parameter="path" }] },
        { name = "ReadResponse" , Variable = [{ name = "v1", value = "1" , type = "int"  },{ name = "toDo", value = "toDo" , type = "object" }] } ]

[DomainModels]
DomainModel = [{ name = "ToDoDomains" , Variable = [{ name = "Sno", value = "1" , type = "int" , dbtype="int" },{ name = "Description", value = "1" , type = "string" , dbtype="varchar(50)" }] }]


[Mapping]
Map = [{ name = "convertToDoDomainToDo" , from = "ToDoDomains" , to = "ToDo" , type="domain2dto", primary = "Sno" , primarytype = "int",  VariableMapping = [{ from = "Sno", to = "Id" , type="int"    },{ from = "Description", to = "Title"  }]},
     { name = "convertToDoToDoDomain" , from = "ToDo" , to = "ToDoDomains" , type="dto2domain", VariableMapping = [{ from = "Id", to = "Sno" , type="int"   },{ from = "Title", to = "Description" }]} ]

[CommandToEvent]
Command =  [{name = "TestCreateCommand", events= [{name = "ToDoDomainsEventCreated"}]},
            {name = "TestUpdateCommand", events= [{name = "ToDoDomainsEventUpdated"}]},
            {name = "TestDeleteCommand", events= [{name = "ToDoDomainsEventDeleted"}]}]