package gogfile

import (
	"strings"
)

func javaFileloc(templateFile string, apiName string) string {
	if strings.Contains(templateFile, "application") {
		return "src/main/java/com/gogenetic/restful/"
	}
	if strings.Contains(templateFile, "model") {
		return "src/main/java/com/gogenetic/restful/" + strings.ToLower(apiName) + "/"
	}
	return ""
}

func javaFileName(templateFile string, conf AutoGenerated) string {
	if strings.Contains(templateFile, "pom") {
		return "pom.xml"
	}
	if strings.Contains(templateFile, "proto-") {
		return conf.API.Name + "-service.proto"
	}
	if strings.Contains(templateFile, "docker") {
		return "Dockerfile"
	}
	if strings.Contains(templateFile, "application") {
		return "Application.java"
	}
	if strings.Contains(templateFile, "model") {
		return conf.DomainModels.DomainModel[0].Name + ".java"
	}
	return ""
}
