
[[ArchType]]
name = "mysql"
projects = ["mysql"]

[[projects]] 
name =  "mysql"
templateBasePath = "liquibase/"
templates = [
		"liquibasetemplate.tpl"
		,"docker/dockertemplate.tpl"
]
OutputDir="/sql"