package arch

import (
	"gogenetic/gogexec"
	"gogenetic/gogfile"
	"os"

	"gogenetic/data"
)

func GoLangArch(conf data.AutoGeneratedCli, archType string, templateFile string) {
	var userTomlDir = conf.Gogenetic.TomlDir

	//4. Set Value to the CLI Stucts input
	if archType == "es-sync-with-cqrs" {

		conf.Gogenetic.Escqrsread = "go/es-cqrs-read/"
		conf.Gogenetic.Escqrscud = "go/es-cqrs-cud/"
		conf.Gogenetic.Esreadoutput = conf.Gogenetic.OutDir + "/es-read-output"
		conf.Gogenetic.Eventstorereadoutput = conf.Gogenetic.OutDir + "/eventstore-read-output"
		conf.Gogenetic.Cudoutput = conf.Gogenetic.OutDir + "/es-cud-output"

		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"escqrsreadreadmetemplate.tpl", conf.Gogenetic.Esreadoutput)

		conf.Gogenetic.TomlDir = "toml/eventstore-read.toml"
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"eventstorecqrsreadmetemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormesdomaintemplate.tpl", conf.Gogenetic.Cudoutput)

		conf.Gogenetic.TomlDir = userTomlDir
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"proto-grpcresttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"servicenatstemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcrestservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"cmdservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natssubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natspubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"servicetodomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natsconutilclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"configtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"devconftemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"commandtoeventtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormcommandstoredomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"escqrscudreadmetemplate.tpl", conf.Gogenetic.Cudoutput)

		gogexec.MoveTo(conf.Gogenetic.Esreadoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Esreadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Esreadoutput)

		gogexec.MoveTo("../..")

		gogexec.MoveTo(conf.Gogenetic.Cudoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Cudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Cudoutput)

		gogexec.MoveTo("../..")

		gogexec.MoveTo(conf.Gogenetic.Eventstorereadoutput)

		conf.API.Name = "EventStore"
		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Eventstorereadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Eventstorereadoutput)

	}

	if archType == "es-async-with-cqrs" {

		conf.Gogenetic.Escqrsread = "go/es-cqrs-read/"
		conf.Gogenetic.Escqrscud = "go/es-cqrs-cud/"
		conf.Gogenetic.Esreadoutput = conf.Gogenetic.OutDir + "/es-read-output"
		conf.Gogenetic.Eventstorereadoutput = conf.Gogenetic.OutDir + "/eventstore-read-output"
		conf.Gogenetic.Cudoutput = conf.Gogenetic.OutDir + "/es-cud-output"

		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"escqrsreadreadmetemplate.tpl", conf.Gogenetic.Esreadoutput)

		conf.Gogenetic.TomlDir = "toml/eventstore-read.toml"
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormesdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"eventstorecqrsreadmetemplate.tpl", conf.Gogenetic.Eventstorereadoutput)

		conf.Gogenetic.TomlDir = userTomlDir
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"proto-grpcresttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"serviceasyncnatstemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcrestservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"cmdservertemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"grpcclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natssubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natspubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"servicetodomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natsconutilclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"configtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"devconftemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"commandtoeventtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormcommandstoredomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"escqrscudreadmetemplate.tpl", conf.Gogenetic.Cudoutput)

		gogexec.MoveTo(conf.Gogenetic.Esreadoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Esreadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Esreadoutput)

		gogexec.MoveTo("../..")

		gogexec.MoveTo(conf.Gogenetic.Cudoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Cudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Cudoutput)

		gogexec.MoveTo("../..")

		gogexec.MoveTo(conf.Gogenetic.Eventstorereadoutput)

		conf.API.Name = "EventStore"

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Eventstorereadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Eventstorereadoutput)

	}

	if archType == "es-async-with-cqrs-read" {

		conf.Gogenetic.TomlDir = "toml/eventstore-read.toml"
		conf.Gogenetic.Escqrsread = "go/es-cqrs-read/"
		conf.Gogenetic.Esreadoutput = conf.Gogenetic.OutDir + "/es-read-output"

		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Esreadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"escqrsreadreadmetemplate.tpl", conf.Gogenetic.Esreadoutput)

		gogexec.MoveTo(conf.Gogenetic.Esreadoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Esreadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Esreadoutput)

	}

	if archType == "es-cqrs-eventstore-read" {

		conf.Gogenetic.Escqrsread = "go/es-cqrs-read/"
		conf.Gogenetic.Eventstorereadoutput = conf.Gogenetic.OutDir + "/eventstore-read-output"

		conf.Gogenetic.TomlDir = "toml/eventstore-read.toml"
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"proto-grpcresttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"servicecrudtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcrestservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"cmdservertemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"grpcclienttemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"xormdomaintemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"configtemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"devconftemplate.tpl", conf.Gogenetic.Eventstorereadoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrsread+"eventstorecqrsreadmetemplate.tpl", conf.Gogenetic.Eventstorereadoutput)

		gogexec.MoveTo(conf.Gogenetic.Cudoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Cudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Cudoutput)

		gogexec.MoveTo("../..")

		gogexec.MoveTo(conf.Gogenetic.Eventstorereadoutput)

		conf.API.Name = "EventStore"

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Eventstorereadoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Eventstorereadoutput)
	}

	if archType == "es-async-with-cqrs-cmd-event-handler-cud" {

		conf.Gogenetic.TomlDir = "toml/eventstore-read.toml"
		conf.Gogenetic.Escqrscud = "go/es-cqrs-cud/"
		conf.Gogenetic.Cudoutput = conf.Gogenetic.OutDir + "/es-cud-output"
		// To-do dont know what this is for
	}

	if archType == "es-async-cmdhandler-with-cqrs" {

		conf.Gogenetic.Escqrscud = "go/es-cqrs-cud/"
		conf.Gogenetic.Cudoutput = conf.Gogenetic.OutDir + "/es-cmdhandler-cud-output"

		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natssubclientchtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natspubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natsconutilclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"configtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"devconftemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormesdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"commandtoeventtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormcommandstoredomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"escqrscudcmdeventhandlerreadmetemplate.tpl", conf.Gogenetic.Cudoutput)

		gogexec.MoveTo(conf.Gogenetic.Cudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Cudoutput)

	}

	if archType == "es-async-eventhandler-with-cqrs" {

		conf.Gogenetic.Escqrscud = "go/es-cqrs-cud/"
		conf.Gogenetic.Cudoutput = conf.Gogenetic.OutDir + "/es-eventhandler-cud-output"

		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"proto-grpcresttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natssubclientehtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natspubclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"servicetodomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"natsconutilclienttemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"configtemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"devconftemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormesdomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"xormcommandstoredomaintemplate.tpl", conf.Gogenetic.Cudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Escqrscud+"escqrscudcmdeventhandlerreadmetemplate.tpl", conf.Gogenetic.Cudoutput)

		gogexec.MoveTo(conf.Gogenetic.Cudoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Cudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Cudoutput)

	}

	if archType == "crud" {

		conf.Gogenetic.Crud = "go/"
		conf.Gogenetic.Crudoutput = conf.Gogenetic.OutDir + "/crud"

		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"proto-grpcresttemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"servicecrudtemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"grpcservertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"grpcrestservertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"cmdservertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"grpcclienttemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"xormdomaintemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"configtemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"devconftemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"docker/dockertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"crudreadmetemplate.tpl", conf.Gogenetic.Crudoutput)

		gogexec.MoveTo(conf.Gogenetic.Crudoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Crudoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Crudoutput)

	}

	if archType == "es-sync-without-cqrs" {
		conf.Gogenetic.Eswithoutcqrs = "go/"
		conf.Gogenetic.Eswithoutcqrsoutput = conf.Gogenetic.OutDir + "/es-without-cqrs"

		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"proto-grpcresttemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"servicenatstemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"grpcservertemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"grpcrestservertemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"cmdservertemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"grpcclienttemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"xormdomaintemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"natssubclienttemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"natspubclienttemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"servicetodomaintemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"natsconutilclienttemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"configtemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"devconftemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Eswithoutcqrs+"eswithoutcqrscudreadmetemplate.tpl", conf.Gogenetic.Eswithoutcqrsoutput)

		gogexec.MoveTo(conf.Gogenetic.Eswithoutcqrsoutput)

		runGRPC(conf, conf.Gogenetic.Dir+"/"+conf.Gogenetic.Eswithoutcqrsoutput)

		formatCode(conf.Gogenetic.Dir + "/" + conf.Gogenetic.Eswithoutcqrsoutput)
	}

	gogexec.MoveTo(conf.Gogenetic.Dir + "/" + conf.Gogenetic.OutDir)
	applyGoMod(conf.Gogenetic.OutDir)
}

func runGRPC(conf data.AutoGeneratedCli, dir string) {
	grpcargs := []string{"--proto_path=proto", "-I/usr/local/include", "-I.", "-I" + os.Getenv("GOPATH") + "/src", "-I" + os.Getenv("GOPATH") + "/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis", "--go_out=plugins=grpc:proto", conf.API.Name + "-service.proto"}
	gogexec.ExecuteProtoCmd(grpcargs)

	grpcgatewayargs := []string{"--proto_path=proto", "-I/usr/local/include", "-I.", "-I" + os.Getenv("GOPATH") + "/src", "-I" + os.Getenv("GOPATH") + "/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis", "--grpc-gateway_out=logtostderr=true:proto", conf.API.Name + "-service.proto"}
	gogexec.ExecuteProtoCmd(grpcgatewayargs)

	runSwagger(conf, "proto", dir)

}

func runSwagger(conf data.AutoGeneratedCli, protoDir string, outputDir string) {
	dist := protoDir + "/dist"
	gogexec.CreateDirIfNotExist(dist)
	grpcswaggerargs := []string{"--proto_path=proto", "-I/usr/local/include", "-I.", "-I" + os.Getenv("GOPATH") + "/src", "-I" + os.Getenv("GOPATH") + "/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis", "--swagger_out=logtostderr=true:" + dist, conf.API.Name + "-service.proto"}
	gogexec.ExecuteProtoCmd(grpcswaggerargs)
	gogexec.SwaggerTemplate(outputDir+"/"+dist, conf.API.Name+"-service.swagger.json")
}

func formatCode(dir string) {
	gofmtargs := []string{"-w", dir}
	gogexec.ExecuteCmd("gofmt", gofmtargs)
}

func applyGoMod(dir string) {
	gomodargs := []string{"mod", "init", dir}
	gogexec.ExecuteCmd("go", gomodargs)
}
