package arch

import (
	"gogenetic/config"
	"gogenetic/gogexec"
	"gogenetic/gogfile"
	"strconv"
	"strings"

	"gogenetic/data"

	"github.com/spf13/viper"
)

func JavaLangArch(conf data.AutoGeneratedCli, archType string) {
	//4. Set Value to the CLI Stucts input

	if archType == "crud" {

		conf.Gogenetic.Crud = "java/"
		conf.Gogenetic.Crudoutput = conf.Gogenetic.OutDir + "/crud"

		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"docker/dockertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"pomtemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"applicationtemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"domainmodeltemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"repositorytemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"servicetemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"controllertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"mapstructmappertemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"configtemplate.tpl", conf.Gogenetic.Crudoutput)
		gogfile.CreateFile(conf, conf.Gogenetic.Crud+"crudreadmetemplate.tpl", conf.Gogenetic.Crudoutput)

		noOfModel := len(conf.Models.Model)
		for i := 0; i < noOfModel; i++ {
			conf.Models.Index = strconv.Itoa(i)
			gogfile.CreateFile(conf, conf.Gogenetic.Crud+"modeltemplate.tpl", conf.Gogenetic.Crudoutput)
		}

		gogfile.CreateFile(conf, "go/proto-grpcresttemplate.tpl", conf.Gogenetic.Crudoutput)
		gogexec.MoveTo(conf.Gogenetic.Crudoutput)
		runSwaggerJava(conf, ".", conf.Gogenetic.Crudoutput)
		gogexec.MoveTo("../..")
		gogexec.RemoveFile(conf.Gogenetic.Crudoutput + "/" + conf.API.Name + "-service.proto")

	}

}

func JavaLangArchConf(conf data.AutoGeneratedCli, archType string) {

	var userTomlDir = conf.Gogenetic.TomlDir
	var userApiName = conf.API.Name
	var archTypes config.ArchTypes

	viper.Unmarshal(&archTypes)

	for _, arch := range archTypes.ArchType {
		if archType == arch.Name {
			for _, archPgt := range arch.Projects {
				for _, project := range archTypes.Projects {
					if archPgt == project.Name {

						if project.TemplateToml == "" {
							conf.Gogenetic.TomlDir = userTomlDir
						} else {
							conf.Gogenetic.TomlDir = project.TemplateToml
						}

						if project.ApiName == "" {
							conf.API.Name = userApiName
						} else {
							conf.API.Name = project.ApiName
						}

						for _, projectTpl := range project.Templates {

							if strings.Contains("modeltemplate.tpl", projectTpl) {
								noOfModel := len(conf.Models.Model)
								for i := 0; i < noOfModel; i++ {
									conf.Models.Index = strconv.Itoa(i)
									gogfile.CreateFile(conf, project.TemplateBasePath+projectTpl, conf.Gogenetic.OutDir+project.OutputDir)
								}
							} else {
								gogfile.CreateFile(conf, project.TemplateBasePath+projectTpl, conf.Gogenetic.OutDir+project.OutputDir)
							}
						}

					}

				}
			}

		}

	}

}
