# {{.API.Name}} CUD generated by gogenetic Golang
A Go micro services eco-system, designed to make development and maintaince of microservice life easier.

# Goal
To make application CRUD application with GRPC, HTTP, NATS, DB support & External config in golang



# Build Gogenetic HTTP/GRPC Server
    cd {{.Architechture.Outputdir}}
    
    go build cmd/main/{{.API.Name}}-cmdserver.go

# Build Gogenetic NATS Client

    cd {{.Architechture.Outputdir}}

    go build client/nats/sub/Test-sub-client.go 
    

# Run Gogenetic HTTP/GRPC Server

    cd {{.Architechture.Outputdir}}
    ./{{.API.Name}}-cmdserver

# Run Gogenetic NATS Client

    ./{{.API.Name}}-sub-client

## Config Supported

    External Config File to load HTTP, GRPC, NATS Port and DB Connection

    config-dev.json

    {
    "GRPCPort": 4040,
    "HTTPPort": 8080,
    "DBCon": "root:@tcp(localhost:3306)/GOGENETIC_SCHEMA?charset=utf8&parseTime=True&loc=Local",
    "NATSurl": "nats://127.0.0.1:4222",
    "UserCreds":"",
    "ShowTime":true,
    "NATSSubj": "Test"
    }

## Swagger UI Doc 

    http://127.0.0.1:8080/docs/

## Prometheus 

    http://127.0.0.1:8080/metrics