# {{.API.Name}} CRUD generated by gogenetic Java
A Go micro services eco-system, designed to make development and maintaince of microservice life easier.

# Goal
To make application CRUD application with  HTTP, DB support & External config in src/main/resources



# Build Gogenetic
    cd {{.Architechture.Outputdir}}
    mvn clean install
    

# Run Gogenetic

    cd {{.Architechture.Outputdir}}
    mvn clean spring-boot:run  

## Config Supported

    External Config File to load Port and DB Connection

    application.properties

    server.port = 9090
    spring.application.name = Todo

    spring.datasource.url=jdbc:mysql://localhost:3306/GOGENETIC_SCHEMA
    spring.datasource.username=root
    spring.datasource.password=
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver

    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
    spring.jpa.generate-ddl=true
    spring.jpa.show-sql=true


    